variable "project" {
  description = "The GCP project ID to apply the IAM policy to"
  type        = string
}

variable "policy_data" {
  description = "The policy data JSON string generated by google_iam_policy data source representing all bindings"
  type        = string
}