#!/bin/sh
set -e

"$1" import -var-file environments/sg.tfvars 'module.athena_workgroup.aws_athena_workgroup.this' 'primary'
"$1" import -var-file environments/sg.tfvars 'module.cloudformation_stack.aws_cloudformation_stack.this' 'arn:aws:cloudformation:ap-southeast-1:714114208215:stack/stulyze-app/0fc6fa90-2d31-11ee-94b5-062fa483a518'
"$1" import -var-file environments/sg.tfvars 'module.iam_policy["all"].aws_iam_policy.this' 'arn:aws:iam::714114208215:policy/All'
"$1" import -var-file environments/sg.tfvars 'module.iam_policy["amazonsagemaker_executionpolicy_20231125t142640"].aws_iam_policy.this' 'arn:aws:iam::714114208215:policy/service-role/AmazonSageMaker-ExecutionPolicy-20231125T142640'
"$1" import -var-file environments/sg.tfvars 'module.iam_policy["amazonsagemakerservicecatalogproductsuserole_20231125t142608"].aws_iam_policy.this' 'arn:aws:iam::714114208215:policy/service-role/AmazonSageMakerServiceCatalogProductsUseRole-20231125T142608'
"$1" import -var-file environments/sg.tfvars 'module.iam_policy["aws_iam_policy_4"].aws_iam_policy.this' 'arn:aws:iam::714114208215:policy/service-role/Cognito-1690255817691'
"$1" import -var-file environments/sg.tfvars 'module.iam_role["awsserviceroleforamazonelasticfilesystem"].aws_iam_role.this' 'AWSServiceRoleForAmazonElasticFileSystem'
"$1" import -var-file environments/sg.tfvars 'module.iam_role["awsserviceroleforapigateway"].aws_iam_role.this' 'AWSServiceRoleForAPIGateway'
"$1" import -var-file environments/sg.tfvars 'module.iam_role["awsserviceroleforamazonsagemakernotebooks"].aws_iam_role.this' 'AWSServiceRoleForAmazonSageMakerNotebooks'
"$1" import -var-file environments/sg.tfvars 'module.iam_role["awsserviceroleforsupport"].aws_iam_role.this' 'AWSServiceRoleForSupport'
"$1" import -var-file environments/sg.tfvars 'module.internet_gateway.aws_internet_gateway.this' 'igw-02aec4b4978ee2879'
"$1" import -var-file environments/sg.tfvars 'module.keyspaces_ap_southeast_1["system"].aws_keyspaces_keyspace.this' 'system'
"$1" import -var-file environments/sg.tfvars 'module.keyspaces_ap_southeast_1["system_schema_mcs"].aws_keyspaces_keyspace.this' 'system_schema_mcs'
"$1" import -var-file environments/sg.tfvars 'module.keyspaces_eu_central_1["system"].aws_keyspaces_keyspace.this' 'system'
"$1" import -var-file environments/sg.tfvars 'module.keyspaces_eu_central_1["system_multiregion_info"].aws_keyspaces_keyspace.this' 'system_multiregion_info'
"$1" import -var-file environments/sg.tfvars 'module.keyspaces_us_west_1["system_schema_mcs"].aws_keyspaces_keyspace.this' 'system_schema_mcs'
"$1" import -var-file environments/sg.tfvars 'module.default_network_acl.aws_default_network_acl.this' 'acl-0b1b4715940488f98'
"$1" import -var-file environments/sg.tfvars 'module.route_table.aws_route_table.this' 'rtb-011310e36ec8c4564'
"$1" import -var-file environments/sg.tfvars 'module.security_group["security_group_for_outbound_nfs_d_e7rysy0e6m17"].aws_security_group.this' 'sg-09b139379252db92a'
"$1" import -var-file environments/sg.tfvars 'module.default_security_group.aws_default_security_group.this' 'sg-0b58b33cabde6d297'
"$1" import -var-file environments/sg.tfvars 'module.security_group["security_group_for_inbound_nfs_d_e7rysy0e6m17"].aws_security_group.this' 'sg-0c5fca3d0f618a860'
"$1" import -var-file environments/sg.tfvars 'module.default_subnet["aws_subnet_1"].aws_default_subnet.this' 'subnet-0aec9ccc3d679b626'
"$1" import -var-file environments/sg.tfvars 'module.default_subnet["aws_subnet_2"].aws_default_subnet.this' 'subnet-0df3e594471580676'
"$1" import -var-file environments/sg.tfvars 'module.default_vpc.aws_default_vpc.this' 'vpc-05fed6e9ac0f64a6e'
